
name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn package -DskipTests=true
      
    - name: Build
      run: mvn -f delivery/ms-pagamento/pom.xml

    - name: Test with Maven
      run: mvn test
